name: FastSL-py
channels:
  - defaults
dependencies:
  - anaconda
  - pip
  - python=3.6.1
  - pip:
    - cobra==0.11.3
    - future==0.16.0
    - joblib==0.11
    - lxml==4.1.1
    - mpmath==1.0.0
    - numpy==1.14.1
    - optlang==1.3.0
    - pandas==0.22.0
    - python-dateutil==2.6.1
    - pytz==2018.3
    - ruamel.yaml==0.14.12
    - six==1.11.0
    - swiglpk==1.4.4
    - sympy==1.1.1
    - tabulate==0.8.2
    - tqdm==4.19.6

